### ISSUE TITLE
Return on completed action

### ISSUE THREAD

**Issue by jamesAtcodeninja** [ariesjia/vue-actions#1]
Normally a store action can  `return` something to the dispatcher. For example - 
```
store.action.LOGOUT = function (context) { return true; };
```
and anytime a piece of code calls it
```
const result = this.$store.dispatch('LOGOUT');
```
It returns `true`. Is there some way we can emulate this in vuex-actions?

edit: Never mind, this is not something achievable since the context object is not the same.

**Comment by ariesjia** [comment]
sorry to replay late. 
in vuex-actions  is the same result .

`export const actions = {
  LOGOUT: actionCreator('LOGOUT', function({ commit }) {
    return true
  }),
}`

`const result = this.$store.dispatch('LOGOUT');`

the result is `true`  .

vuex-actions also support async action

`
export const actions = {
  getShareRecord: actionCreator('GET_SHARE_RECORD', function({ commit }, shareId) {
    return shareAPIs.getShareRecord(shareId)  // will return promise
  }),
}
`
in container files  you can get the promise
`this.$store.dispatch('getShareRecord').then((res) => { console.log(res)  })`
